name: Build Plastimatch as Shared Library (DCMTK Only)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++ make git cmake \
            libblas-dev liblapack-dev libsqlite3-dev \
            libdcmtk-dev libinsighttoolkit5-dev

      - name: Criar diretório de build
        run: mkdir -p build

      - name: Configurar CMake
        run: |
          cd build
          cmake .. \
            -DUSE_DCMTK=ON \
            -DUSE_CUDA=OFF \
            -DUSE_FFTW=OFF \
            -DDCMTK_FORCE_FPIC_ON_UNIX=ON \
            -DBUILD_SHARED_LIBS=ON \
            -DUSE_SYSTEM_ITK=ON

      - name: Compilar o Plastimatch
        run: |
          cd build
          make -j$(nproc)

      - name: Upload da biblioteca compartilhada como artefato
        uses: actions/upload-artifact@v3
        with:
          name: plastimatch-shared-library
          # Ajuste o caminho abaixo se o .so for gerado em outra pasta.
          path: build/lib/libplastimatch.so
