name: Build Plastimatch Master (DCMTK Only)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            g++ make git cmake \
            libblas-dev liblapack-dev libsqlite3-dev \
            libdcmtk-dev

      - name: Criar diretório de build
        run: mkdir -p build

      - name: Configurar CMake
        run: |
          cd build
          cmake .. \
            -DUSE_DCMTK=ON \
            -DUSE_CUDA=OFF \
            -DUSE_FFTW=OFF

      - name: Compilar o Plastimatch
        run: |
          cd build
          make -j$(nproc)
